### ISSUE TITLE
Feat: Admin API should poll for individual application status

### ISSUE THREAD

**Issue by awalias** [supabase/supabase-admin-api#29]
- [ ] add a route `/status/[application]` which will check systemd to see if the service is active and has been running for more than a couple of seconds (for some application we may want to check that the service has an active db connection)

- [ ] create a monitoring cron that polls these endpoints and pushes to BQ
- [ ] add a query/dashboard which calculates uptime per application and total

**Comment by icecream78** [comment]
@awalias Please, can you answer few questions?

1. I don't understand how to ensure that application has an active db connection. Can you make some tips about that? Only by parsing logs it's difficult implement. And what are services that you want get such info?
2. Where this cron notation have to be implemented? Directly in this server? And what is BQ?=) I don't know this reduction
3. How to calculate per application/total uptime? For this one we need external storage where we save periodic up/down info  but now this server doesn't have such connector

**Comment by steve-chavez** [comment]
> How to calculate per application/total uptime? 

@icecream78 These are built-in in systemd:
```bash
## uptime
systemctl show -p ActiveEnterTimestamp some.service
ActiveEnterTimestamp=Tue 2020-12-01 08:37:05 -05

## general info
systemctl show some.service
## ...
```

> And what is BQ?

BigQuery I believe.

**Comment by darora** [comment]
Now handled via metrics
