### ISSUE TITLE
Github action to build for ARM/Graviton

### ISSUE THREAD

**Issue by awalias** [supabase/supabase-admin-api#31]
https://medium.com/@nabil.servais/using-github-actions-to-test-your-go-code-on-arm64-ce581e646cb

https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee

https://github.community/t/does-github-actions-support-multiple-os-architectures/16526

**Comment by darora** [comment]
Going to take a crack at this today
