### ISSUE TITLE
Upgrade GetLogContents to use journalctl

### ISSUE THREAD

**Issue by awalias** [supabase/supabase-admin-api#55]
https://github.com/supabase/supabase-admin-api/blob/55edf8cf16134f1cf25c174ccb624ef955c87fe5/api/logs.go#L28

the files used above no longer contain the logs, they are managed by [journalctl](https://www.loggly.com/ultimate-guide/using-journalctl/)

**Comment by inian** [comment]
Duplicate https://github.com/supabase/infrastructure/issues/2294
